image: "rust:latest"

stages:
  - test
  - secret-detection

test:cargo:
  stage: test
  script:
    - cargo test --release

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection
