[package]
name = "rustpp"
version = "4.1.0"
edition = "2021"
authors = ["Francesco149", "midnightblue"]
description = "Pure Rust port of oppai-ng: osu! difficulty and pp calculator"
license = "Unlicense"

[lib]
name = "rustpp"
path = "src/lib.rs"

[[bin]]
name = "oppai"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
